services:
  emulators:
    build:
      context: .
      dockerfile: emulators/Dockerfile
    ports:
      - "7020:7020"
      - "7021:7021"
      - "7022:7022"
      - "7023:7023"
      - "7024:7024"
      - "4400:4400"
      - "4500:4500"
      - "9150:9150"
    volumes:
      - ./packages/functions/dist:/app/packages/functions/dist
      - ./packages/shared/dist:/app/packages/shared/dist
    env_file:
      - path: ./packages/functions/.env
        required: false
